name: Pull Request Comment Trigger Example
on:
  pull_request:
    types: [opened, edited, reopened]
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_number }}
  cancel-in-progress: true

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: geopipe/pull-request-comment-trigger@feature/handle-review-comments
        id: check
        with:
          trigger: '#hello'
          reaction: eyes
          fail_if_not_mergeable: true
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo "${PULL_REQUEST_INFO}"'
        id: echo_json
        if: steps.check.outputs.triggered == 'true'
        env: 
          PULL_REQUEST_INFO: ${{ steps.check.outputs.pull_request }}
      - uses: LouisBrunner/checks-action@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          output: |
            {"summary":${{ steps.echo_json.outputs.summary || "yo ho" }}}
          sha: ${{ fromJSON(steps.check.outputs.pull_request).head.sha }}

  eyes:
    runs-on: ubuntu-latest
    steps:
      - uses: geopipe/pull-request-comment-trigger@feature/handle-review-comments
        id: check
        with:
          trigger: '#look'
          reaction: eyes
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'

  rocket:
    runs-on: ubuntu-latest
    steps:
      - uses: geopipe/pull-request-comment-trigger@feature/handle-review-comments
        id: check
        with:
          trigger: '#deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'